### ISSUE TITLE
Bounding box

### ISSUE THREAD

**Issue by Zumbalamambo** [PCJohn/FaceDetect#1]
How do I draw bounding box around face?

**Comment by ZlaaM** [comment]
@Zumbalamambo  please are you solved it?
i need the same one 
help me

**Comment by ZlaaM** [comment]
@Zumbalamambo

**Comment by Zumbalamambo** [comment]
yes I have solved it

**Comment by ZlaaM** [comment]
@Zumbalamambo  
please I need the code 
can you send it to me 
this my email (  allaayakoob@gmail.com )
thanks alot

**Comment by ZlaaM** [comment]
@Zumbalamambo 
Please if you solve all  the problems of the code send me the whole code because I tried to solve it but I could not solve it all
I desperately need it
Thank you so much

**Comment by ZlaaM** [comment]
@Zumbalamambo

**Comment by ZlaaM** [comment]
😢

**Comment by Zumbalamambo** [comment]
@ZlaaM bro.. use MTCNN or yolo instead. it is more robust than this. Do you need the code for those archs?

**Comment by ZlaaM** [comment]
please I complete a code of detect facial landmark based on CNN
and I want to detect the face in same network

**Comment by ZlaaM** [comment]
i solved many problems of this code , but i do not know how to make a
bounding box around the detected face,
if you can send me the code .. thanks a lot

**Comment by ZlaaM** [comment]
@
please I complete a code of detect facial landmark based on CNN 
and I want to detect the face in same network 
i solved many problems of this code , but i do not know how to make a bounding box around the detected face,
if you can send me the code .. thanks a lot

**Comment by ZlaaM** [comment]
@Zumbalamambo

**Comment by ZlaaM** [comment]
🤔

**Comment by ZlaaM** [comment]
@Zumbalamambo 
 please sir I just want to know how draw bounding box around face

**Comment by ZlaaM** [comment]
@Zumbalamambo

**Comment by ZlaaM** [comment]
!!!!!!!!!!!!!
@Zumbalamambo

**Comment by ZlaaM** [comment]
@Zumbalamambo

**Comment by ZlaaM** [comment]
@Zumbalamambo

**Comment by ZlaaM** [comment]
@Zumbalamambo  !!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ZlaaM** [comment]
@Zumbalamambo 
please sir, Why do not you answer my request?!!!!!!!!!!!!!!!!!!
My  request will not affect youو But it will serve me a lot

**Comment by ZlaaM** [comment]
@Zumbalamambo 
!!!!!!?????????????

**Comment by ZlaaM** [comment]
???????????

**Comment by PCJohn** [comment]
To draw bounding boxes around faces, you can use the binary masks. This is a simple problem of finding connected components (find the contours in the mask) and drawing boxes around them.
See answer 1 in this link: https://stackoverflow.com/questions/16538774/dealing-with-contours-and-bounding-rectangle-in-opencv-2-4-python-2-7
and section 7.a on this page: https://docs.opencv.org/3.1.0/dd/d49/tutorial_py_contour_features.html
