### ISSUE TITLE
xrange is not defined

### ISSUE THREAD

**Issue by Hpareek07** [PCJohn/FaceDetect#2]
I am getting this error while running the demo.py file.
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    faces,mask = FaceFinder.localize(img,model_path)
  File "C:\Users\Harshit\AppData\Local\Programs\Python\Python35\FaceDetect\FaceFinder.py", line 111, in localize
    for i in xrange(0, img.shape[1]-bx, X_STEP):
NameError: name 'xrange' is not defined

**Comment by Hpareek07** [comment]
Now that problem is resolved by changing xrange to range.
I have got another problem that is it is not showing me faces.
![image](https://user-images.githubusercontent.com/24519886/30781397-db59538e-a13b-11e7-83b9-dd7357ccade7.png)

**Comment by PCJohn** [comment]
You've probably got Python 3.x. xrange() not defined is a common problem when you're trying to move from Python 2.7 (which is what I wrote this in) to 3.x.
The code should display 3 windows, one with the mask, one with the faces and one with the original photo. Are the other 2 being displayed properly? Which version of OpenCV are you using?

**Comment by ZlaaM** [comment]
i have the same problem ... the version of opencv i used is 3.4.2
the code displayed the three windows @https://github.com/PCJohn

**Comment by ZlaaM** [comment]
@PCJohn

**Comment by Eumenides-K** [comment]
I have the same problem too and the version of my opecv is the latest 4.1.0.25. I really wonder what the problem is...

**Comment by PCJohn** [comment]
Please read my answer above. This is not related to the version of OpenCV, but the version of _Python_. 
See this link:  https://stackoverflow.com/questions/17192158/nameerror-global-name-xrange-is-not-defined-in-python-3
